In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from apyori import apriori

In [10]:
df = pd.read_csv('Market_Basket_Optimisation.csv', header = None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
transactions = []
for i in range(0, 7499):
    transactions.append([str(df.values[i,j]) for j in range(0, 19)])

In [18]:
rules = apriori(transactions = transactions, min_support = 0.003, min_confidence = 0.2, min_lift = 3, min_length = 2, max_length = 2)

In [19]:
results = list(rules)
results

[RelationRecord(items=frozenset({'light cream', 'chicken'}), support=0.004533937858381117, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.842659069325735)]),
 RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005734097879717296, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.30069930069930073, lift=3.796202114383933)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005867448993199093, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.37288135593220345, lift=4.707470182046454)]),
 RelationRecord(items=frozenset({'fromage blanc', 'honey'}), support=0.0033337778370449394, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.162893809209077)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.01600213361781571, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.291116093143691)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005334044539271903, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.8396354420009726)]),
 RelationRecord(items=frozenset({'light cream', 'olive oil'}), support=0.003200426723563142, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820512, lift=3.1201955583294323)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.008001066808907855, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.129670591906603)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.0050673423123083075, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050848, lift=4.505470528712371)])]

In [20]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['ITEM_1', 'ITEM_2', 'Support', 'Confidence', 'Lift'])

In [21]:
clean = resultsinDataFrame.nlargest(n = 15, columns = 'Support')
clean.sort_values(by=['Support','Confidence','Lift'],ascending=False)

                 ITEM_1       ITEM_2   Support  Confidence      Lift
4         herb & pepper  ground beef  0.016002    0.323450  3.291116
7     whole wheat pasta    olive oil  0.008001    0.271493  4.129671
2                 pasta     escalope  0.005867    0.372881  4.707470
1  mushroom cream sauce     escalope  0.005734    0.300699  3.796202
5          tomato sauce  ground beef  0.005334    0.377358  3.839635
8                 pasta       shrimp  0.005067    0.322034  4.505471
0           light cream      chicken  0.004534    0.290598  4.842659
3         fromage blanc        honey  0.003334    0.245098  5.162894
6           light cream    olive oil  0.003200    0.205128  3.120196